import { Link } from "react-router-dom";
import { ArrowRight, BatteryCharging, BookOpen, Bot, CheckCircle2, CircuitBoard, Lightbulb, MapPin, Radio, ShieldCheck, Sun, Users } from "lucide-react";
import SEO from "@/components/SEO";
import { Button } from "@/components/ui/button";
import trackerPresentationImage from "@/assets/presentation.jpg";
import solarGeneratorImage from "@/assets/solar-generator.jpg";
import smartDriveImage from "@/assets/robot-car-1.jpg";
import electronicsKitImage from "@/assets/IMG_6989.JPG";
import roboticsVehicleImage from "@/assets/abrob-robotics-vehicle.png";
import studentsLearningImage from "@/assets/students-learning.png";

const solutions = [
  { icon: MapPin, eyebrow: "Security & fleet visibility", title: "ABROB-GT Tracker", copy: "A dual-mode GPS tracking solution for vehicles and valuable assets, with online monitoring, SMS fallback, alerts and practical deployment support.", image: trackerPresentationImage, to: "/tracker", action: "Explore ABROB-GT" },
  { icon: Sun, eyebrow: "Clean energy", title: "AB-Solar Power System", copy: "Small-scale solar and battery systems designed to provide dependable DC power for homes, learning spaces and small businesses.", image: solarGeneratorImage, to: "/projects/ab-solar-power-system", action: "View the power system" },
  { icon: Bot, eyebrow: "Robotics platform", title: "ABROB SmartDrive", copy: "An ESP32-based robotic vehicle platform for learning embedded programming, automation, sensors and autonomous-robotics foundations.", image: smartDriveImage, to: "/projects/abrob-smartdrive", action: "Explore SmartDrive" },
  { icon: CircuitBoard, eyebrow: "Embedded engineering", title: "Electronics & IoT Platform", copy: "Reusable hardware, connectivity and cloud building blocks that turn sensors, controllers and ideas into tested connected products.", image: electronicsKitImage, to: "/projects/electronics-iot-platform", action: "Explore the platform" },
  { icon: Radio, eyebrow: "Intelligent systems", title: "Robotics & Automation", copy: "Practical automation concepts combining mechanics, electronics, embedded control, sensing and intelligent decision-making.", image: roboticsVehicleImage, to: "/projects/robotics-automation", action: "Explore automation" },
  { icon: BookOpen, eyebrow: "Skills & education", title: "STEM & Robotics Education", copy: "Hands-on programmes, kits and workshops that help learners build real capability in electronics, coding, robotics, IoT and AI.", image: studentsLearningImage, to: "/education", action: "Explore education" },
];

const solutionPrinciples = [
  "Engineering-led design grounded in real operating conditions",
  "A clear path from prototype and pilot to practical deployment",
  "Knowledge transfer that helps people use and grow the solution",
];

const Solutions = () => (
  <>
    <SEO title="Solutions | ABROB INDUSTRY" description="Explore ABROB INDUSTRY solutions in GPS tracking, solar power, robotics, automation, IoT engineering and STEM education." />
    <main className="min-h-screen overflow-hidden bg-white">
      <section className="relative overflow-hidden border-b border-slate-200 bg-[#f7fafc]">
        <div className="absolute -right-28 -top-28 h-[32rem] w-[32rem] rounded-full bg-[#09bde8]/15 blur-3xl" />
        <div className="absolute -bottom-36 left-1/4 h-80 w-80 rounded-full bg-[#061b5c]/10 blur-3xl" />
        <div className="container relative mx-auto grid gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-28">
          <div className="reveal max-w-3xl"><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#09bde8]/30 bg-[#09bde8]/10 px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-[#0879c9]"><Lightbulb className="h-4 w-4" /> ABROB INDUSTRY solutions</p><h1 className="text-5xl leading-[1.02] text-[#061b5c] sm:text-6xl lg:text-7xl">Technology built for <span className="text-[#0879c9]">real impact.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600 sm:text-xl">We design practical systems for safer mobility, dependable energy, connected operations, intelligent machines and future-ready technical skills.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#solutions"><Button size="lg" className="h-14 rounded-full bg-[#061b5c] px-7 text-base font-bold text-white hover:bg-[#0b2d7f]">Explore solutions <ArrowRight className="ml-2 h-5 w-5" /></Button></a><Link to="/contact?intent=consultation#consultation"><Button size="lg" variant="outline" className="h-14 rounded-full border-slate-300 px-7 text-base font-bold text-[#061b5c] hover:border-[#09bde8] hover:bg-[#09bde8]/10">Discuss your challenge</Button></Link></div></div>
          <div className="reveal grid gap-4 sm:grid-cols-2" style={{ animationDelay: ".12s" }}>{[{ value: "01", label: "Connected security", icon: ShieldCheck }, { value: "02", label: "Energy systems", icon: BatteryCharging }, { value: "03", label: "Robotics & IoT", icon: Bot }, { value: "04", label: "STEM learning", icon: Users }].map(({ value, label, icon: Icon }) => <div key={value} className="rounded-3xl border border-white/80 bg-white/85 p-6 shadow-card backdrop-blur transition hover:-translate-y-1 hover:border-[#09bde8]/60 hover:shadow-glow"><Icon className="h-7 w-7 text-[#0879c9]" /><p className="mt-10 font-poppins text-3xl font-bold text-[#09bde8]">{value}</p><p className="mt-1 font-bold text-[#061b5c]">{label}</p></div>)}</div>
        </div>
      </section>

      <section id="solutions" className="scroll-mt-20 py-20 sm:py-24"><div className="container mx-auto px-4 sm:px-6"><div className="mb-12 max-w-3xl"><p className="mb-3 text-sm font-bold uppercase tracking-[.2em] text-[#0879c9]">Our solution portfolio</p><h2 className="text-4xl text-[#061b5c] sm:text-5xl">One industry. Multiple ways to move forward.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Each solution is shaped around a practical need and can be explored on its own. ABROB-GT has its dedicated product page; the remaining solutions connect to their project or programme details.</p></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{solutions.map(({ icon: Icon, eyebrow, title, copy, image, to, action }, index) => <article key={title} style={{ animationDelay: `${index * 0.08}s` }} className="reveal group flex flex-col overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-card transition duration-500 hover:-translate-y-2 hover:border-[#09bde8]/60 hover:shadow-glow"><div className="relative h-52 overflow-hidden bg-[#061b5c]"><img src={image} alt={title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#061b5c]/70 via-transparent to-transparent" /><div className="absolute bottom-4 left-5 rounded-xl bg-white/90 p-3 text-[#0879c9] backdrop-blur"><Icon className="h-5 w-5" /></div></div><div className="flex flex-1 flex-col p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#0879c9]">{eyebrow}</p><h3 className="mt-3 text-2xl font-bold text-[#061b5c]">{title}</h3><p className="mt-3 flex-1 leading-7 text-slate-600">{copy}</p><Link to={to} className="mt-7 inline-flex items-center font-bold text-[#0879c9]">{action} <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" /></Link></div></article>)}</div></div></section>

      <section className="border-y border-slate-200 bg-[#f7fafc] py-20 sm:py-24"><div className="container mx-auto grid gap-12 px-4 sm:px-6 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="mb-3 text-sm font-bold uppercase tracking-[.2em] text-[#0879c9]">How we work</p><h2 className="text-4xl text-[#061b5c] sm:text-5xl">From a real need to a useful system.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Whether the outcome is a deployed product, a pilot, a workshop or an R&D prototype, our approach stays focused on what people need to achieve.</p></div><div className="space-y-4">{[["01", "Understand the context", "We start with the challenge, the people using the solution and the conditions it must work in."], ["02", "Build and test", "We turn the idea into a focused system, prototype or learning experience and improve it through testing."], ["03", "Deploy and enable", "We support practical rollout and help users, partners or learners build confidence with the solution."]].map(([number, title, copy]) => <div key={number} className="flex gap-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><span className="font-poppins text-2xl font-bold text-[#09bde8]">{number}</span><div><h3 className="text-xl font-bold text-[#061b5c]">{title}</h3><p className="mt-2 leading-7 text-slate-600">{copy}</p></div></div>)}</div></div></section>

      <section className="bg-[#061b5c] py-20 text-white sm:py-24"><div className="container mx-auto grid gap-10 px-4 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="mb-3 text-sm font-bold uppercase tracking-[.2em] text-[#09bde8]">A practical partner</p><h2 className="max-w-2xl text-4xl leading-tight sm:text-5xl">Built around the realities of the people who use it.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-blue-100/75">Our products, platforms and programmes share the same foundation: useful engineering, local understanding and a clear route to impact.</p><Link to="/contact?intent=consultation#consultation"><Button size="lg" className="mt-8 h-14 rounded-full bg-[#09bde8] px-8 font-bold text-[#061b5c] hover:bg-white">Start a conversation <ArrowRight className="ml-2 h-5 w-5" /></Button></Link></div><div className="space-y-4">{solutionPrinciples.map((principle) => <div key={principle} className="flex items-start gap-3 rounded-2xl border border-white/10 bg-white/5 p-5"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-[#09bde8]" /><p className="font-semibold leading-6 text-blue-50">{principle}</p></div>)}</div></div></section>
    </main>
  </>
);

export default Solutions;
